#!/bin/sh
export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig
meson setup build \
    --prefix=/usr \
    --libdir=/usr/lib64 \
    -Dtests=disabled \
    -Ddocumentation=disabled \
    -Dbuildtype=release
ninja -C build
DESTDIR="$1" ninja -C build install
