#!/bin/sh
export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig
meson setup build --prefix=/usr -Dbuildtype=release -Dxkb-base=/usr/share/X11/xkb
ninja -C build
DESTDIR="$1" ninja -C build install
