#!/bin/sh
./configure \
    --prefix=/usr \
    --libdir=/usr/lib64 \
    --bindir=/usr/bin \
    --sbindir=/usr/sbin \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib64 \
    --with-rootprefix=/usr \
    --with-rootlibdir=/usr/lib64 \
    --disable-manpages \
    --disable-static
make -j$(nproc)
make DESTDIR="$1" install
