#!/bin/sh
export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
./configure --libdir=/usr/lib --prefix=/usr --with-xinitdir=/etc/X11/xinit
make -j$(nproc)
make DESTDIR="$1" install
