#!/bin/sh
./configure --prefix=/usr --sbindir=/sbin --sysconfdir=/etc \
  --disable-efiemu --disable-grub-themes --disable-nls \
  --with-platform=pc --target=x86_64
make -j$(nproc)
make DESTDIR="$1" install
