#!/bin/sh
export PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
cmake -B build -G Ninja \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTS=OFF -DUPDATE_DEPS=OFF -DBUILD_CUBE=ON -DBUILD_VULKANINFO=ON
cmake --build build -j$(nproc)
DESTDIR="$1" cmake --install build
