#!/bin/sh
# Pure zsh, nothing to compile: the plugin tree is dropped under
# /usr/share/zsh/plugins and sourced from ~/.zshrc.
install -dm755 "$1/usr/share/zsh/plugins/zsh-syntax-highlighting"
cp -a . "$1/usr/share/zsh/plugins/zsh-syntax-highlighting/"
