#!/bin/sh
make defconfig
sed -i 's/# CONFIG_STATIC is not set/CONFIG_STATIC=y/' .config
sed -i 's/CONFIG_TC=y/# CONFIG_TC is not set/' .config
make -j$(nproc)
mkdir -p "$1/usr/lib/busybox-static"
cp busybox "$1/usr/lib/busybox-static/busybox"
