#!/bin/sh
export PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
./configure --prefix=/usr --libdir=/usr/lib --enable-unicode --enable-jit --disable-static
make -j$(nproc)
make DESTDIR="$1" install
