#!/bin/sh
mkdir build
cd build
../configure --prefix=/usr \
  --enable-languages=c,c++ \
  --disable-multilib \
  --disable-libsanitizer \
  --without-isl \
  --with-gmp=/usr \
  --with-mpfr=/usr \
  --with-mpc=/usr
make -j$(nproc)
make DESTDIR="$1" install
