#!/bin/sh
printf '#!/bin/sh\nexit 0\n' > /usr/bin/makeinfo
chmod +x /usr/bin/makeinfo
mkdir build
cd build
../configure --libdir=/usr/lib --prefix=/usr --disable-nls --disable-werror --disable-plugins --disable-gold --disable-gprofng lt_cv_ar_interface=gnu
make -j$(nproc)
make DESTDIR="$1" install
