#!/bin/sh
export PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
meson setup build --prefix=/usr --libdir=/usr/lib -Dbuildtype=release -Dtests=false -Dglx=yes -Dx11=true
ninja -C build
DESTDIR="$1" ninja -C build install
