#!/bin/sh
cmake -S . -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_FLAGS="-fpermissive" \
    -DENABLE_CTEST=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DENABLE_OPT=OFF \
    -DENABLE_SPVREMAPPER=OFF
cmake --build build -j$(nproc)
DESTDIR="$1" cmake --install build
