#!/bin/sh
make defconfig
sed -i 's/CONFIG_TC=y/# CONFIG_TC is not set/' .config
sed -i 's/CONFIG_NANDWRITE=y/# CONFIG_NANDWRITE is not set/' .config
sed -i 's/CONFIG_NANDDUMP=y/# CONFIG_NANDDUMP is not set/' .config
sed -i 's/CONFIG_UBIATTACH=y/# CONFIG_UBIATTACH is not set/' .config
sed -i 's/CONFIG_UBIDETACH=y/# CONFIG_UBIDETACH is not set/' .config
sed -i 's/CONFIG_UBIMKVOL=y/# CONFIG_UBIMKVOL is not set/' .config
sed -i 's/CONFIG_UBIRMVOL=y/# CONFIG_UBIRMVOL is not set/' .config
sed -i 's/CONFIG_UBIRSVOL=y/# CONFIG_UBIRSVOL is not set/' .config
sed -i 's/CONFIG_UBIUPDATEVOL=y/# CONFIG_UBIUPDATEVOL is not set/' .config
sed -i 's/CONFIG_UBIRENAME=y/# CONFIG_UBIRENAME is not set/' .config
make olddefconfig
make -j$(nproc)
mkdir -p "$1/bin"
cp busybox "$1/bin/busybox"
"$1/bin/busybox" --install -s "$1/bin"
