#!/bin/sh
SITE=$(python3 -c "import site; print(site.getsitepackages()[0])")

mkdir -p "$1$SITE" "$1/usr/bin"

cp -r mesonbuild "$1$SITE/"

cat > "$1/usr/bin/meson" << 'EOF'
#!/usr/bin/env python3
import sys
from mesonbuild.mesonmain import main
sys.exit(main())
EOF
chmod +x "$1/usr/bin/meson"
