#!/bin/sh
CFLAGS="-O2" ./configure --libdir=/usr/lib --prefix=/usr --disable-debuginfod --disable-libdebuginfod \
  --without-bzip2 --without-lzma --without-zstd --disable-nls
make -j$(nproc) -C lib
make -j$(nproc) -C libelf
make -j$(nproc) -C libdw
make DESTDIR="$1" -C lib install
make DESTDIR="$1" -C libelf install
make DESTDIR="$1" -C libdw install
