#!/bin/sh
CFLAGS="-O2" ./configure --libdir=/usr/lib --prefix=/usr --disable-debuginfod --disable-libdebuginfod \
  --without-bzip2 --without-lzma --without-zstd --disable-nls
for d in lib libelf libebl backends libcpu libdw libdwfl libdwelf; do
  make -j$(nproc) -C $d
done
for d in lib libelf libdw libdwfl libdwelf; do
  make DESTDIR="$1" -C $d install
done
