#!/bin/sh
CXXFLAGS="-fpermissive" ./configure --libdir=/usr/lib --prefix=/usr --disable-debuginfod --disable-libdebuginfod \
  --without-bzip2 --without-lzma --without-zstd --disable-nls
make -j$(nproc)
make DESTDIR="$1" install
