#!/bin/sh
make CC=gcc CONFIG_SHELL=/usr/bin/bash defconfig
scripts/config --disable CONFIG_DEBUG_INFO_BTF
scripts/config --disable CONFIG_STACK_VALIDATION
scripts/config --disable CONFIG_UNWINDER_ORC
scripts/config --enable CONFIG_UNWINDER_FRAME_POINTER
scripts/config --enable CONFIG_EXT4_FS
scripts/config --enable CONFIG_ATA
scripts/config --enable CONFIG_ATA_PIIX
scripts/config --enable CONFIG_SATA_AHCI
scripts/config --enable CONFIG_NVME_CORE
scripts/config --enable CONFIG_BLK_DEV_NVME
scripts/config --enable CONFIG_VIRTIO_BLK
scripts/config --enable CONFIG_SCSI_VIRTIO
scripts/config --disable CONFIG_EXT4_USE_FOR_EXT2
make CC=gcc CONFIG_SHELL=/usr/bin/bash olddefconfig
make CC=gcc CONFIG_SHELL=/usr/bin/bash -j$(nproc)
mkdir -p "$1/lib/modules"
make CC=gcc CONFIG_SHELL=/usr/bin/bash INSTALL_MOD_PATH="$1" modules_install
mkdir -p "$1/boot"
cp arch/x86_64/boot/bzImage "$1/boot/vmlinuz"
