#!/bin/sh
make defconfig
scripts/config --disable CONFIG_DEBUG_INFO_BTF
make olddefconfig
make -j$(nproc)
make INSTALL_MOD_PATH="$1" modules_install
mkdir -p "$1/boot"
cp arch/x86_64/boot/bzImage "$1/boot/vmlinuz"
cp System.map "$1/boot/System.map"
