#!/bin/sh
PYVER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
export PYTHONPATH=/usr/lib/python$PYVER/site-packages
meson setup build \
    --prefix=/usr \
    -Dgallium-drivers=nouveau,softpipe \
    -Dvulkan-drivers= \
    -Dglx=dri \
    -Dopengl=true \
    -Dgles1=disabled \
    -Dgles2=disabled \
    -Dllvm=disabled \
    -Dshared-llvm=disabled \
    -Dplatforms=x11 \
    -Dglvnd=disabled \
    -Dgallium-vdpau=disabled \
    -Dgallium-va=disabled \
    -Dbuildtype=release
ninja -C build
DESTDIR="$1" ninja -C build install
