#!/bin/sh
export PYTHONPATH=$(python3 -c "import site; print(site.getsitepackages()[0])")
meson setup build \
    --prefix=/usr \
    -Dgallium-drivers=nouveau,swrast \
    -Dvulkan-drivers= \
    -Dglx=dri \
    -Dopengl=true \
    -Dgles1=disabled \
    -Dgles2=disabled \
    -Dllvm=disabled \
    -Dshared-llvm=disabled \
    -Dplatforms=x11 \
    -Dbuildtype=release
ninja -C build
DESTDIR="$1" ninja -C build install
