#!/bin/sh
./configure --libdir=/usr/lib64 --prefix=/usr --with-openssl --without-libpsl --disable-manual --without-ca-embed --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt
make -j$(nproc)
make DESTDIR="$1" install
