#!/bin/sh
./configure CFLAGS="-Dmemset_explicit=memset" \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-static \
    --with-group-name-max-length=32
make -j$(nproc)
make DESTDIR="$1" install
